"""Project layout, the shared ``project.json`` manifest, and file operations.

Everything that collaborators need to share (chapter order, titles, tags,
statuses, export settings) is kept in ``project.json`` inside the repository,
so it travels with git pushes and pulls.
"""
import json
import re
import shutil
from pathlib import Path

from .htmlfmt import format_html
from .paths import doc_format, is_text, rel_path, safe_path

MANIFEST = "project.json"
BIBLIOGRAPHY = "references.bib"
EXPORT_DIR = "exports"
IGNORED_DIRS = {".git", EXPORT_DIR, "node_modules", "__pycache__"}

GITIGNORE = """# Generated by Document Manager
exports/
.DS_Store
Thumbs.db
*.aux
*.log
*.synctex.gz
"""

# Keep binary attachments out of line-ending conversion; normalise text files.
GITATTRIBUTES = """* text=auto
*.pdf binary
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.docx binary
"""

EXTENSIONS = {"markdown": ".md", "latex": ".tex", "html": ".html"}

STATUSES = ["idea", "outline", "draft", "revision", "final"]


def default_manifest(title: str, kind: str = "book", description: str = "",
                     authors: list[str] | None = None) -> dict:
    return {
        "title": title,
        "subtitle": "",
        "authors": authors or [],
        "kind": kind,
        "description": description,
        "manuscript": [],
        "files": {},
        "export": {"toc": True, "number_sections": False, "pdf_engine": "xelatex", "csl": ""},
    }


def read_manifest(root: Path) -> dict:
    path = root / MANIFEST
    data = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            data = {}
    base = default_manifest(root.name)
    base.update({k: v for k, v in data.items() if v is not None})
    base["export"] = {**default_manifest("")["export"], **(data.get("export") or {})}
    return base


def write_manifest(root: Path, manifest: dict) -> None:
    # Stable key order + trailing newline keeps git diffs of the manifest small.
    (root / MANIFEST).write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def starter_content(fmt: str, title: str) -> str:
    if fmt == "latex":
        return f"\\section{{{title}}}\n\n"
    if fmt == "html":
        return f"<h1>{escape_html(title)}</h1>\n<p></p>\n"
    return f"# {title}\n\n"


def escape_html(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return slug[:60] or "untitled"


def scaffold(root: Path, title: str, kind: str, fmt: str, description: str, authors: list[str]) -> None:
    """Create the initial directory structure for a new project."""
    for d in ("manuscript", "notes", "attachments"):
        (root / d).mkdir(parents=True, exist_ok=True)
    (root / "attachments" / ".gitkeep").touch()
    (root / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    (root / ".gitattributes").write_text(GITATTRIBUTES, encoding="utf-8")
    (root / BIBLIOGRAPHY).write_text("", encoding="utf-8")

    manifest = default_manifest(title, kind, description, authors)
    ext = EXTENSIONS[fmt]
    first_title = "Introduction" if kind == "book" else "Abstract"
    first = f"manuscript/01-{slugify(first_title)}{ext}"
    write_text(root, first, starter_content(fmt, first_title))
    manifest["manuscript"].append(first)
    manifest["files"][first] = {"title": first_title, "status": "draft", "tags": [], "target_words": 0}

    write_text(root, "notes/ideas.md", "# Ideas\n\n- \n")
    manifest["files"]["notes/ideas.md"] = {"title": "Ideas", "status": "idea", "tags": ["notes"], "target_words": 0}

    readme = f"# {title}\n\n{description}\n\nManaged with Document Manager.\n"
    (root / "README.md").write_text(readme, encoding="utf-8")
    write_manifest(root, manifest)


def ensure_manifest(root: Path) -> None:
    """For cloned repos that were not created by this app."""
    if not (root / MANIFEST).exists():
        manifest = default_manifest(root.name)
        manuscript = root / "manuscript"
        if manuscript.is_dir():
            manifest["manuscript"] = sorted(
                rel_path(root, p) for p in manuscript.rglob("*") if p.is_file() and doc_format(p.name)
            )
        write_manifest(root, manifest)


# ---------------------------------------------------------------- files

def tree(root: Path) -> list[dict]:
    """Flat list of files and directories (sorted), excluding internal folders."""
    items = []

    def walk(directory: Path):
        for child in sorted(directory.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
            if child.name in IGNORED_DIRS or child.name == ".gitkeep":
                continue
            rel = rel_path(root, child)
            if child.is_dir():
                items.append({"path": rel, "type": "dir"})
                walk(child)
            else:
                items.append({
                    "path": rel, "type": "file", "size": child.stat().st_size,
                    "format": doc_format(rel), "text": is_text(rel),
                })

    walk(root)
    return items


def read_text(root: Path, rel: str) -> str:
    return safe_path(root, rel).read_text(encoding="utf-8", errors="replace")


def write_text(root: Path, rel: str, content: str) -> None:
    target = safe_path(root, rel)
    if doc_format(rel) == "html":
        content = format_html(content)
    content = content.replace("\r\n", "\n")
    if content and not content.endswith("\n"):
        content += "\n"  # POSIX text files; avoids "No newline at end of file" noise in diffs.
    target.parent.mkdir(parents=True, exist_ok=True)
    # Always LF line endings so collaborators on Windows/macOS/Linux produce identical diffs.
    target.write_text(content.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def move(root: Path, src: str, dest: str) -> None:
    source = safe_path(root, src)
    target = safe_path(root, dest)
    if target.exists():
        raise FileExistsError(f"{dest} already exists")
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(source), str(target))

    manifest = read_manifest(root)
    prefix = src.rstrip("/") + "/"

    def remap(p: str) -> str:
        if p == src:
            return dest
        if p.startswith(prefix):
            return dest.rstrip("/") + "/" + p[len(prefix):]
        return p

    manifest["manuscript"] = [remap(p) for p in manifest["manuscript"]]
    manifest["files"] = {remap(k): v for k, v in manifest["files"].items()}
    write_manifest(root, manifest)


def delete(root: Path, rel: str) -> None:
    target = safe_path(root, rel)
    if rel in (MANIFEST,):
        raise PermissionError("project.json cannot be deleted")
    if target.is_dir():
        shutil.rmtree(target)
    elif target.exists():
        target.unlink()
    manifest = read_manifest(root)
    prefix = rel.rstrip("/") + "/"
    manifest["manuscript"] = [p for p in manifest["manuscript"] if p != rel and not p.startswith(prefix)]
    manifest["files"] = {k: v for k, v in manifest["files"].items() if k != rel and not k.startswith(prefix)}
    write_manifest(root, manifest)


# ---------------------------------------------------------------- words & search

_TAG_RE = re.compile(r"<[^>]+>")
_LATEX_CMD_RE = re.compile(r"\\[a-zA-Z@]+\*?(\[[^\]]*\])?")
_MD_SYNTAX_RE = re.compile(r"[#*_`>\[\]()!|~-]")
_WORD_RE = re.compile(r"[\w'’]+", re.UNICODE)


def plain_text(content: str, fmt: str | None) -> str:
    if fmt == "html":
        return _TAG_RE.sub(" ", content)
    if fmt == "latex":
        content = re.sub(r"(?<!\\)%.*", "", content)
        return _LATEX_CMD_RE.sub(" ", content).replace("{", " ").replace("}", " ")
    if fmt == "markdown":
        return _MD_SYNTAX_RE.sub(" ", content)
    return content


def word_count(content: str, fmt: str | None) -> int:
    return len(_WORD_RE.findall(plain_text(content, fmt)))


def stats(root: Path) -> dict:
    manifest = read_manifest(root)
    chapters = []
    total = 0
    for rel in manifest["manuscript"]:
        try:
            content = read_text(root, rel)
        except (FileNotFoundError, ValueError):
            content = ""
        words = word_count(content, doc_format(rel))
        total += words
        meta = manifest["files"].get(rel, {})
        chapters.append({"path": rel, "words": words, "target_words": meta.get("target_words") or 0,
                         "status": meta.get("status", "draft")})
    target = sum(c["target_words"] for c in chapters)
    return {"total_words": total, "target_words": target, "chapters": chapters}


def search(root: Path, query: str, limit: int = 200) -> list[dict]:
    query = query.strip()
    if not query:
        return []
    needle = query.lower()
    results = []
    for item in tree(root):
        if item["type"] != "file" or not item["text"]:
            continue
        try:
            lines = read_text(root, item["path"]).splitlines()
        except OSError:
            continue
        for number, line in enumerate(lines, 1):
            if needle in line.lower():
                snippet = plain_text(line, item["format"]).strip() if item["format"] == "html" else line.strip()
                results.append({"path": item["path"], "line": number, "snippet": snippet[:240]})
                if len(results) >= limit:
                    return results
    return results
