# Generated by Django 5.2.7 on 2026-10-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="calendar",
            field=models.CharField(default="auto", max_length=10),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="theme",
            field=models.CharField(default="system", max_length=8),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="ui_language",
            field=models.CharField(default="en", max_length=8),
        ),
    ]
