# Generated by Django 5.2.7 on 2026-10-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ui_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="PythonEnv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("kind", models.CharField(max_length=8)),
                ("created_by_app", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.AddField(
            model_name="appsettings",
            name="conda_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="package_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="env_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.CreateModel(
            name="NotebookKernel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("kernel", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_kernels",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "path")},
            },
        ),
    ]
